#!/bin/bash
# Flow Dashboard Demo Script
# Demonstrates typical usage workflow

echo "=================================================="
echo "Flow Execution Dashboard - Demo Workflow"
echo "=================================================="
echo ""

echo "1. View current dashboard status:"
echo "   $ python3 view_dashboard.py"
echo ""
python3 view_dashboard.py
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "2. Check which flows need testing:"
echo "   $ python3 view_dashboard.py --untested"
echo ""
python3 view_dashboard.py --untested | head -30
echo "   ... (showing first few flows)"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "3. View flows organized by category:"
echo "   $ python3 view_dashboard.py --by-category"
echo ""
python3 view_dashboard.py --by-category | head -50
echo "   ... (showing first few categories)"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "4. EXAMPLE: Record a test result"
echo "   (This is a simulation - not actually updating)"
echo ""
echo "   If you ran 'parallel-research' test, you would run:"
echo ""
echo "   $ python3 update_dashboard.py parallel-research \\"
echo "       --status success \\"
echo "       --duration 90 \\"
echo "       --quality 9.5 \\"
echo "       --scenario 'Research AI communication protocols' \\"
echo "       --notes 'Excellent multi-perspective synthesis'"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "5. EXAMPLE: Add strengths and improvements"
echo "   (This is a simulation - not actually updating)"
echo ""
echo "   After testing, document learnings:"
echo ""
echo "   $ python3 update_dashboard.py parallel-research \\"
echo "       --add-strength 'Fast parallel execution'"
echo ""
echo "   $ python3 update_dashboard.py parallel-research \\"
echo "       --add-improvement 'Need better conflict resolution'"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "6. EXAMPLE: Mark flow as validated"
echo "   (This is a simulation - not actually updating)"
echo ""
echo "   After multiple successful tests:"
echo ""
echo "   $ python3 update_dashboard.py parallel-research \\"
echo "       --validate \\"
echo "       --quality 9.5"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "7. View test history:"
echo "   $ python3 view_dashboard.py --history"
echo ""
python3 view_dashboard.py --history
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=================================================="
echo "8. View detailed info for specific category:"
echo "   $ python3 view_dashboard.py --detailed --category governance"
echo ""
python3 view_dashboard.py --detailed --category governance
echo ""

echo "=================================================="
echo "Demo Complete!"
echo "=================================================="
echo ""
echo "Available commands:"
echo "  • python3 view_dashboard.py              # Summary"
echo "  • python3 view_dashboard.py --detailed   # All flows detailed"
echo "  • python3 view_dashboard.py --untested   # Flows needing tests"
echo "  • python3 view_dashboard.py --by-category # Organized by category"
echo "  • python3 view_dashboard.py --history    # Test history"
echo ""
echo "  • python3 update_dashboard.py <flow> --status success --duration 90 --quality 9.0"
echo "  • python3 update_dashboard.py <flow> --validate"
echo "  • python3 update_dashboard.py <flow> --add-strength 'description'"
echo ""
echo "See DASHBOARD-README.md for complete documentation"
echo ""
